# Generated by Django 5.0.1 on 2024-06-01 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default='', max_length=50)),
                ('image', models.CharField(default='', max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=50)),
                ('prenom', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=250)),
                ('pays', models.CharField(default='', max_length=25)),
                ('region', models.CharField(default='', max_length=50)),
                ('ville', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(default='', max_length=25, unique=True)),
                ('biographie', models.CharField(default='', max_length=250)),
                ('image', models.CharField(default='', max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PosteLangues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=25)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
            ],
        ),
        migrations.CreateModel(
            name='PosteFormations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
            ],
        ),
        migrations.CreateModel(
            name='PosteExperiences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
            ],
        ),
        migrations.CreateModel(
            name='PosteDiplomes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
            ],
        ),
        migrations.CreateModel(
            name='PosteCompetences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
            ],
        ),
        migrations.CreateModel(
            name='UserLangues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=25)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserFormations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserExperiences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserDiplomes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompetences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.AddField(
            model_name='postes',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users'),
        ),
        migrations.CreateModel(
            name='UserTitres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=50)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
