# Generated by Django 5.0.1 on 2024-06-01 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=50)),
                ('prenom', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=250)),
                ('pays', models.CharField(default='', max_length=25)),
                ('region', models.CharField(default='', max_length=50)),
                ('ville', models.CharField(default='', max_length=50)),
                ('telephone', models.CharField(default='', max_length=25, unique=True)),
                ('biographie', models.CharField(default='', max_length=250)),
                ('image', models.CharField(default='', max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Titres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=50)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Postes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default='', max_length=50)),
                ('image', models.CharField(default='', max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Langues',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=25)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Formations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Diplomes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='Competences',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
