# Generated by Django 5.0.1 on 2024-06-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postes',
            old_name='image',
            new_name='description',
        ),
        migrations.AddField(
            model_name='postes',
            name='pays',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='postes',
            name='region',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='postes',
            name='telephone',
            field=models.CharField(default='', max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='postes',
            name='ville',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='PosteMissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
            ],
        ),
        migrations.CreateModel(
            name='PosteQualites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
            ],
        ),
    ]
