# Generated by Django 5.0.1 on 2024-06-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_image_postes_description_postes_pays_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postes',
            name='telephone',
            field=models.CharField(default='', max_length=25),
        ),
    ]
