# Generated by Django 5.0.1 on 2024-05-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='prenom',
            field=models.CharField(default='', max_length=50),
        ),
    ]
