# Generated by Django 5.0.1 on 2024-05-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_users_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='createdAt',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='updatedAt',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
