# Generated by Django 5.0.1 on 2024-06-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userqualites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTitres',
            new_name='UserPostes',
        ),
    ]
