# Generated by Django 5.0.1 on 2024-05-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_users_createdat_alter_users_updatedat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postes',
            fields=[
                ('updatedAt', models.DateTimeField(auto_created=True, null=True)),
                ('createdAt', models.DateTimeField(auto_created=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default='', max_length=50)),
                ('image', models.CharField(default='/user.jpg', max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='CentreInterets',
        ),
        migrations.AddField(
            model_name='competences',
            name='projectId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='experiencespro',
            name='projectId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='formations',
            name='projectId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='parcours',
            name='projectId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='competences',
            name='userId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='experiencespro',
            name='userId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='formations',
            name='userId',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='userId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
