# Generated by Django 5.0.1 on 2024-06-05 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_postes_isdeleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.DecimalField(decimal_places=3, max_digits=5)),
                ('globalScore', models.DecimalField(decimal_places=3, max_digits=5)),
                ('competences', models.DecimalField(decimal_places=3, max_digits=5)),
                ('diplomes', models.DecimalField(decimal_places=3, max_digits=5)),
                ('experiences', models.DecimalField(decimal_places=3, max_digits=5)),
                ('qualites', models.DecimalField(decimal_places=3, max_digits=5)),
                ('posteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.postes')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
