# Generated by Django 5.0.1 on 2024-06-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
